# Generated by Django 5.2 on 2025-04-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_description_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap icon class name (e.g., bi-tshirt, bi-toy, bi-person)', max_length=50),
        ),
    ]
