# Generated by Django 5.2 on 2025-04-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Enter a Bootstrap icon class (e.g., bi-tshirt, bi-car, bi-toy)', max_length=50),
        ),
    ]
